name: Build SdfGlue (release)

on:
  push:
    tags:
      - 'release-*'

permissions:
  # required to create and update GitHub releases (latest build)
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      #upload_latest: true
      upload_release: true
      tag_name: ${{ github.ref_name }}